### ISSUE TITLE
Thread support to get full conversation body

### ISSUE THREAD

**Issue by PureSin** [mccannm11/helpscout-api-python#5]
http://developer.helpscout.net/help-desk-api/objects/thread/

Can't get the complete body right now. I'd be happy to add a PR.

**Comment by mccannm11** [comment]
Please send a PR. Thanks!

**Comment by PureSin** [comment]
PR: https://github.com/mccannm11/helpscout-api-python/pull/6

**Comment by PureSin** [comment]
@mccannm11 please take a look at https://github.com/mccannm11/helpscout-api-python/pull/6 when you have time. thanks
