### ISSUE TITLE
Webhooks creation functions missing.

### ISSUE THREAD

**Issue by diraven** [mccannm11/helpscout-api-python#7]
http://developer.helpscout.net/help-desk-api/hooks/create/

**Comment by diraven** [comment]
I guess I can use call_server function for that, but still something native would be nice.

**Comment by mccannm11** [comment]
Webhooks didn't exist when I created this. Feel free to add them!

**Comment by diraven** [comment]
Fair enough. =)

**Comment by diraven** [comment]
I did indeed end up forking it, but changed a lot during development including formatting. I don't think such pull request will be useful, since it violates your coding style...
